"""Multi-layer SQL WHERE clause guard for AI-generated conditions.

This module implements a fail-closed validation pipeline for WHERE clauses
generated by the LLM semantic parser. It follows the industry-standard
"7-layer guardrail" pattern adapted for our architecture:

  Layer 1: String-level blocklist (fast rejection of dangerous keywords)
  Layer 2: AST validation via sqlglot (structural parse + node-type allowlist)
  Layer 3: Column allowlist (only columns from report_columns.json)
  Layer 4: Function blocklist (xp_cmdshell, OPENROWSET, etc.)
  Layer 5: Operator allowlist (only safe comparison/logical operators)

If ANY layer fails, the WHERE clause is rejected and an empty string is
returned — the query still runs, just without the AI-generated condition.

References:
  - ASK-TARA 7-layer guardrail stack (90K queries, 0 incidents)
  - sql-guard by sakura-sky (deterministic policy engine via sqlglot)
  - mcp-sql-guard (AST validation, single read-only SELECT)
  - Semantic Kernel CVE-2026-26030 (AST node-type allowlist)
  - dpriver.com LLM SQL Guard (parse → bind → validate → audit)
"""

import json
import logging
import os
import re
from typing import Any, Dict, Optional, Set, Tuple

logger = logging.getLogger(__name__)

# ============================================================
# Layer 1: String-level blocklist
# ============================================================

# Keywords that must NEVER appear in a WHERE clause.
# These are checked first for fast rejection before parsing.
# Two tiers: word-boundary matched (DML/DDL keywords that could be substrings
# of legitimate column names) and substring matched (symbols/patterns).
_BLOCKED_KEYWORDS_WORD: Set[str] = {
    # DML
    "DROP", "DELETE", "INSERT", "UPDATE", "MERGE", "TRUNCATE",
    "UPSERT",
    # DDL
    "ALTER", "CREATE", "GRANT", "REVOKE", "DENY",
    # System access
    "EXEC", "EXECUTE", "SP_EXECUTESQL", "XP_CMDSHELL",
    "SP_OACREATE", "SP_OAMETHOD", "SP_OADESTROY",
    # Dangerous functions
    "OPENROWSET", "OPENDATASOURCE", "OPENQUERY",
    "SHUTDOWN", "KILL",
    # Information schema / system tables
    "INFORMATION_SCHEMA", "SYSOBJECTS", "SYSCOLUMNS",
    "SYSTABLES",
    # SQL injection patterns
    "WAITFOR",
    # Type casting functions (can be used for injection / data exfiltration)
    "CAST", "CONVERT",
}

_BLOCKED_KEYWORDS_SUBSTRING: Set[str] = {
    # Comment-based injection (symbols that never appear in valid WHERE)
    "--", "/*", "*/",
    # Stacked queries
    ";",
    # Replace INTO is dangerous
    "REPLACE INTO",
    "BULK INSERT",
    "CONVERT_INT", "CAST_INT",
}

# ============================================================
# Layer 4: Function blocklist (checked during AST walk)
# ============================================================

_BLOCKED_FUNCTIONS: Set[str] = {
    "xp_cmdshell", "sp_executesql", "sp_oacreate", "sp_oamethod",
    "sp_oadestroy", "openrowset", "opendatasource", "openquery",
    "bulk_insert", "shutdown", "kill",
    "waitfor", "delay",
    "fn_xsl_file", "fn_get_sql",
    "sp_addextendedproc", "sp_dropextendedproc",
    "sp_recompile", "sp_make_webtask",
    "sp_adduser", "sp_dropuser", "sp_password",
    "sp_grantlogin", "sp_revokelogin",
}

# ============================================================
# Layer 5: Operator allowlist
# ============================================================

# Only these operators are allowed in the WHERE clause.
_ALLOWED_OPERATORS: Set[str] = {
    "=", "<>", "!=", ">", "<", ">=", "<=",
    "AND", "OR", "NOT",
    "LIKE", "IN", "IS", "NULL",
    "BETWEEN",
}

# ============================================================
# Column allowlist (loaded from report_columns/ directory)
# ============================================================

from app.services.column_registry import _load_registry as _load_column_cfg, get_computed_only_names


def _load_allowed_columns() -> Dict[str, Set[str]]:
    """Load allowed SQL column names per report from report_columns/.

    Returns: {report_key: {sql_col1, sql_col2, ...}}
    """
    cfg = _load_column_cfg()
    if not cfg:
        logger.error("Cannot load report_columns for SQL guard")
        return {}

    allowed: Dict[str, Set[str]] = {}
    for report_key, report_cfg in cfg.items():
        cols: Set[str] = set()
        for name, meta in report_cfg.get("columns", {}).items():
            if meta.get("not_available"):
                continue
            # Add the SQL column name (what the SP actually uses)
            sql = meta.get("sql", "")
            if sql:
                cols.add(sql.lower())
            # Also add the catalog key name (what the LLM uses in ai_where)
            # e.g. catalog key "grosswt" maps to SQL "GrossCTWWithLoss"
            # The LLM may generate DI.grosswt OR DI.GrossCTWWithLoss
            if name:
                cols.add(name.lower())
        # Also allow special metric columns
        for name, meta in report_cfg.get("special_metrics", {}).items():
            sql = meta.get("sql", "")
            if sql:
                cols.add(sql.lower())
            if name:
                cols.add(name.lower())
        # Physical base-table columns referenced inside computed expressions
        # (e.g. wip jobtype CASE uses DI.REcnt) are valid refs in ai_where.
        for name, meta in report_cfg.get("columns", {}).items():
            if meta.get("not_available") or not meta.get("computed"):
                continue
            expressions = [meta.get("dimension_expr", ""), meta.get("metric_expr", "")]
            for expr_map_key in ("table_dimension_exprs", "table_metric_exprs"):
                expr_map = meta.get(expr_map_key, {}) or {}
                if isinstance(expr_map, dict):
                    expressions.extend(expr_map.values())
            for expr in expressions:
                if expr:
                    for ref in re.findall(r'DI\.(\w+)', expr, re.IGNORECASE):
                        cols.add(ref.lower())
        # Base columns referenced by name-filter expressions are valid too.
        for expr in (report_cfg.get("name_filter_map") or {}).values():
            for ref in re.findall(r'DI\.(\w+)', expr or "", re.IGNORECASE):
                cols.add(ref.lower())
        # Add physical columns used by computed dimensions and name-based filters
        # CustomerFullName = CONCAT(firstname, ' ', lastname)
        # SalesRep = CONCAT(salesrepfirstname, ' ', salesreplastname)
        # CustomerName = usermanagement_customercode
        cols.update({
            "usermanagement_customerfirstname", "usermanagement_customerlastname",
            "usermanagement_salesrepfirstname", "usermanagement_salesreplastname",
            "usermanagement_customercode",
            "usermanagement_salesrepid", "j_jobno", "stockdocumentno", "stockbarcode",
            "usermanagement_customerid", "entrydate", "jobflowfrom", "issamplelinejob",
            "b2c_orderno", "iswithhallmark", "wastage", "metalrate", "metalamount",
            "totalmetalamount", "mm_totalmetalamount", "design_totalamouont",
            "totalmakingamount", "totaldiamondcost", "totalcolorstonecost",
            "totalprioritychargesamount", "totalmisccost",
            "metaldiamondweightwithloss", "mm_metalweightwithloss",
            "grossctwwithloss", "netweight",
            "platinumwt", "platinumamt",
            "diamondctwwithloss", "diamond_totalpieces",
            "actualcolorstoneweight", "colorstone_totalpieces",
            "totalmiscappliedweight", "totalmiscpcs",
            "discount", "labouramount", "otheramount",
            "unitcost", "totalsettingcost", "totaldiamondhandling",
            "metalpriceratio", "designno", "autocode", "uniqueno", "imgrandomno",
            "groupjob", "stock_suppliercode", "stock_contractorcode",
            "mastermanagement_fg_stocklockername", "job_skuno",
            "mastermanagement_goldtypename", "mastermanagement_goldcolorname",
            "mastermanagement_categoryname", "mastermanagement_subcategoryname",
            "mastermanagement_brandname", "mastermanagement_collectionname",
            "mastermanagement_producttypename",
            "stockmanagement_qcstatusname", "stockmanagement_statusid",
            "metal_type_name",
        })
        allowed[report_key] = cols
    return allowed


_ALLOWED_COLUMNS_CACHE: Dict[str, Set[str]] = _load_allowed_columns()


def _refresh_allowed_columns() -> None:
    """Refresh the cached column allowlist (useful after config updates)."""
    global _ALLOWED_COLUMNS_CACHE
    _ALLOWED_COLUMNS_CACHE = _load_allowed_columns()


# ============================================================
# Layer 1: String-level validation
# ============================================================

def _check_string_blocklist(where_clause: str) -> Tuple[bool, str]:
    """Layer 1: Fast string-level check for blocked keywords.

    Uses word-boundary matching for DML/DDL keywords (to avoid false positives
    on column names like 'DateUpdated') and substring matching for symbols.

    Returns (is_safe, reason). Fail-closed: any match = reject.
    """
    if not where_clause or not where_clause.strip():
        return True, ""

    upper = where_clause.upper()

    # Word-boundary matching for DML/DDL keywords
    for keyword in _BLOCKED_KEYWORDS_WORD:
        if re.search(r'\b' + re.escape(keyword) + r'\b', upper):
            return False, f"Blocked keyword '{keyword}' found in WHERE clause"

    # Substring matching for symbols and patterns
    for keyword in _BLOCKED_KEYWORDS_SUBSTRING:
        if keyword in upper:
            return False, f"Blocked pattern '{keyword}' found in WHERE clause"

    return True, ""


# ============================================================
# Layer 2: AST validation via sqlglot
# ============================================================

def _check_ast(where_clause: str) -> Tuple[bool, str]:
    """Layer 2: Parse the WHERE clause as TSQL and validate AST structure.

    We wrap the WHERE clause in a dummy SELECT to parse it:
      SELECT 1 WHERE <where_clause>

    Then validate:
      - It parses as a single SELECT statement
      - No subqueries (Subquery nodes)
      - No DML/DDL nodes
      - Only allowed expression types (conditions, columns, literals, operators)
      - No blocked functions

    Returns (is_safe, reason).
    """
    if not where_clause or not where_clause.strip():
        return True, ""

    try:
        import sqlglot
        from sqlglot import expressions as exp
    except ImportError:
        logger.error("sqlglot not installed — AST validation unavailable, rejecting WHERE clause (fail-closed)")
        return False, "sqlglot not available — AST validation required"

    # Wrap in a dummy SELECT to parse as a complete statement
    dummy_sql = f"SELECT 1 WHERE {where_clause}"

    try:
        statements = sqlglot.parse(dummy_sql, read="tsql")
    except Exception as e:
        logger.warning("WHERE clause failed to parse as TSQL: %s", e)
        return False, f"Parse error: {e}"

    # Must be exactly one statement
    if len(statements) != 1 or statements[0] is None:
        return False, "Expected exactly one statement"

    parsed = statements[0]

    # Must be a SELECT
    if not isinstance(parsed, exp.Select):
        return False, f"Expected SELECT, got {type(parsed).__name__}"

    # ── Blocked node types ──
    _BLOCKED_NODE_TYPES = (
        exp.Insert,
        exp.Update,
        exp.Delete,
        exp.Drop,
        exp.Alter,
        exp.Create,
        exp.Command,  # EXEC, etc.
        exp.Merge,
    )

    for blocked_type in _BLOCKED_NODE_TYPES:
        if parsed.find(blocked_type):
            return False, f"Blocked statement type: {blocked_type.__name__}"

    # ── Allow subqueries only inside IN expressions (for multi-table lookups) ──
    _ALLOWED_SUBQUERY_TABLES = {
        "stockmanagement_dcb", "jobmanagement_jobmaster", "jobmanagement_jobmaster_closed",
        "usermanagement_systemloginmaster", "stockmanagement_dcbdesigninfo_packageaddwt",
    }
    for subquery_node in parsed.find_all(exp.Subquery):
        parent = subquery_node.parent
        if not isinstance(parent, exp.In):
            return False, "Subqueries are only allowed inside IN expressions"
        # Extract table name from the subquery
        for table_node in subquery_node.find_all(exp.Table):
            tbl_name = table_node.name.lower()
            if tbl_name not in _ALLOWED_SUBQUERY_TABLES:
                return False, f"Table '{tbl_name}' is not allowed in subqueries"
        # Block nested subqueries inside the IN subquery
        nested = subquery_node.find(exp.Subquery)
        if nested is not None and nested is not subquery_node:
            return False, "Nested subqueries are not allowed"

    # ── No UNION / UNION ALL / INTERSECT / EXCEPT ──
    if parsed.find(exp.Union):
        return False, "UNION/INTERSECT/EXCEPT not allowed in WHERE clause"

    # ── Check for blocked functions ──
    for func_node in parsed.find_all(exp.Func):
        func_name = ""
        if hasattr(func_node, "key"):
            func_name = func_node.key
        elif hasattr(func_node, "this") and isinstance(func_node.this, exp.Var):
            func_name = str(func_node.this).lower()

        if func_name and func_name.lower() in _BLOCKED_FUNCTIONS:
            return False, f"Blocked function: {func_name}"

    # ── Check for dangerous function calls by name ──
    for func_node in parsed.find_all(exp.Anonymous):
        if hasattr(func_node, "this") and isinstance(func_node.this, str):
            func_name = func_node.this.lower()
            if func_name in _BLOCKED_FUNCTIONS:
                return False, f"Blocked function: {func_name}"

    return True, ""


# ============================================================
# Layer 3: Column allowlist validation
# ============================================================

def _check_columns(where_clause: str, report_key: str) -> Tuple[bool, str]:
    """Layer 3: Validate that all column references in the WHERE clause
    are in the allowed column set for this report.

    We extract column-like identifiers from the WHERE clause and check
    them against the report's column allowlist.

    Returns (is_safe, reason).
    """
    if not where_clause or not where_clause.strip():
        return True, ""

    allowed = _ALLOWED_COLUMNS_CACHE.get(report_key, set())
    if not allowed:
        # If we can't load the allowlist, fail-closed
        logger.warning("No allowed columns for report %s — rejecting WHERE clause", report_key)
        return False, f"No column allowlist for report {report_key}"

    # Extract column references: only DI.column_name pattern
    # The SP uses DI. as the table alias, so all valid column refs use DI. prefix
    # This automatically skips string literals like 'gold', 'silver' since they
    # don't have the DI. prefix
    col_pattern = re.compile(
        r'DI\.([a-zA-Z_][a-zA-Z0-9_]*)',
        re.IGNORECASE
    )

    found_columns: Set[str] = set()
    for match in col_pattern.finditer(where_clause):
        ident = match.group(1).lower()
        found_columns.add(ident)

    # Check each found column against allowlist
    for col in found_columns:
        if col not in allowed:
            return False, f"Column '{col}' is not in the allowed column list for {report_key}"

    return True, ""


# ============================================================
# Layer 5: Operator validation (string-level)
# ============================================================

def _check_operators(where_clause: str) -> Tuple[bool, str]:
    """Layer 5: Validate that only allowed operators appear in the WHERE clause.

    This is a secondary check after AST validation. We look for
    assignment operators and other dangerous patterns.

    Returns (is_safe, reason).
    """
    if not where_clause or not where_clause.strip():
        return True, ""

    # Block assignment operators (could be used for SQL injection)
    _DANGEROUS_PATTERNS = [
        (r'::', 'double-colon operator'),
        (r'\bINTO\b', 'INTO keyword'),
        (r'\bOUTPUT\b', 'OUTPUT keyword'),
        (r'\bFETCH\b', 'FETCH keyword'),
        (r'\bCURSOR\b', 'CURSOR keyword'),
    ]

    upper = where_clause.upper()
    for pattern, name in _DANGEROUS_PATTERNS:
        if re.search(pattern, upper):
            return False, f"Dangerous pattern: {name}"

    return True, ""


# ============================================================
# Main validation entry point
# ============================================================

def validate_where_clause(where_clause: str, report_key: str) -> Tuple[str, str]:
    """Validate an AI-generated WHERE clause through all guardrail layers.

    Args:
        where_clause: The raw WHERE clause from the LLM (without the WHERE keyword)
        report_key: The report key to validate columns against

    Returns:
        (safe_where_clause, reason)
        - If all layers pass: (original_where_clause, "validated")
        - If any layer fails: ("", reason) — fail-closed, empty WHERE clause
    """
    if not where_clause or not where_clause.strip():
        return "", ""

    where_clause = where_clause.strip()

    # ── Layer 0: Reject computed-only column names ──
    # These are virtual metrics (CASE expressions), not physical base-table columns.
    # If the LLM puts DI.GoldWt > 10 in ai_where, it will cause a SQL error.
    # The set is loaded from report_columns/*.json so new reports don't need code changes.
    _COMPUTED_ONLY_NAMES = get_computed_only_names(report_key)
    upper_clause = where_clause.upper()
    for name in _COMPUTED_ONLY_NAMES:
        if f"DI.{name.upper()}" in upper_clause:
            logger.warning("SQL Guard Layer 0 REJECTED: computed column %s in ai_where", name)
            return "", f"Computed column '{name}' cannot be used in ai_where"

    # Length limit: prevent buffer overflow / DoS via extremely long clauses
    _MAX_WHERE_LENGTH = 2000
    if len(where_clause) > _MAX_WHERE_LENGTH:
        logger.warning("SQL Guard: WHERE clause exceeds %d chars (got %d), rejecting", _MAX_WHERE_LENGTH, len(where_clause))
        return "", f"WHERE clause exceeds maximum length of {_MAX_WHERE_LENGTH} characters"

    # Remove leading "WHERE" or "AND" or "OR" if present
    where_clause = re.sub(r'^(WHERE|AND|OR)\s+', '', where_clause, flags=re.IGNORECASE)

    logger.info("SQL Guard: validating WHERE clause for report=%s len=%d: %s",
                report_key, len(where_clause), where_clause)

    # ── Layer 1: String blocklist ──
    safe, reason = _check_string_blocklist(where_clause)
    if not safe:
        logger.warning("SQL Guard Layer 1 REJECTED: %s | WHERE: %s", reason, where_clause[:200])
        return "", reason

    # ── Layer 2: AST validation ──
    safe, reason = _check_ast(where_clause)
    if not safe:
        logger.warning("SQL Guard Layer 2 REJECTED: %s | WHERE: %s", reason, where_clause[:200])
        return "", reason

    # ── Layer 3: Column allowlist ──
    safe, reason = _check_columns(where_clause, report_key)
    if not safe:
        logger.warning("SQL Guard Layer 3 REJECTED: %s | WHERE: %s", reason, where_clause[:200])
        return "", reason

    # ── Layer 5: Operator validation ──
    safe, reason = _check_operators(where_clause)
    if not safe:
        logger.warning("SQL Guard Layer 5 REJECTED: %s | WHERE: %s", reason, where_clause[:200])
        return "", reason

    logger.info("SQL Guard: WHERE clause PASSED all layers")
    return where_clause, "validated"


def is_safe(where_clause: str, report_key: str) -> bool:
    """Quick boolean check for whether a WHERE clause is safe."""
    safe_clause, _ = validate_where_clause(where_clause, report_key)
    return bool(safe_clause)
